### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by keirashea**
@molexted

### CODE REVIEW

**Comment by no-lex** [comment]
I think your branch `lab3` is a fork of `lab2`, and I think you're gonna have a nasty merge conflict if you merge/change `lab2`, since I see your `lab2` in the staged changes here.

You might want to wipe this branch and make sure it's properly forked from `master` to avoid this.

**Comment by keirashea** [comment]
@oliviatessa

**Comment by keirashea** [comment]
I don't think I can fix the branches without losing comments. If its okay with the TA I am probably only going to merge this branch with master once both lab2 and lab3 are ready.

**Comment by oliviatessa** [comment]
Hi Keira, 

Here are my comments on your lab 3: 

P.1
- I'm a little confused why you initially chose 4sigma as your threshold. Is there any intuitive reason why you did this? 
- Great job using an example from your own research when discussing the removal of bad data from the dataset! 

P.2
- This problem is pretty special because of the symmetry. If it wasn't symmetric, how would you solve this problem? Miguel initially gave the "blue book" hint because he wanted you to make the connection between the 2D Gaussian and the Rayleigh distribution. Like I said, what you’ve done for this problem is fine, but in the future knowing the relationships between distributions could make problems like these easier. 

P.3
- This is the correct sigma, but the incorrect probability. We're interested in the probability from negative infinity to 6800. "More signal-like" in this case is less than or equal to 6800. 

Best, 
Olivia

**Pull request closed without merging**
